#!/usr/bin/env bash
# One-time bootstrap for remote OpenTofu state.
#
# Creates a private, versioned, encrypted S3 bucket for the tfstate, writes
# backend.hcl (NOT committed — the bucket name embeds the AWS account ID and
# this repo is public; the file is regenerated by this script from your AWS
# credentials), and runs `tofu init -migrate-state` to move any local state in.
#
# Safe to re-run: skips whatever already exists. From a fresh clone, running
# this script is all that's needed to reconnect to the existing deployment.
set -euo pipefail
cd "$(dirname "$0")"

REGION="${AWS_REGION:-us-east-1}"
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
BUCKET="radiobot-tfstate-${ACCOUNT_ID}"

if aws s3api head-bucket --bucket "$BUCKET" 2>/dev/null; then
  echo "State bucket $BUCKET already exists"
else
  echo "Creating state bucket $BUCKET in $REGION"
  if [ "$REGION" = "us-east-1" ]; then
    aws s3api create-bucket --bucket "$BUCKET" --region "$REGION"
  else
    aws s3api create-bucket --bucket "$BUCKET" --region "$REGION" \
      --create-bucket-configuration "LocationConstraint=$REGION"
  fi
  aws s3api put-bucket-versioning --bucket "$BUCKET" \
    --versioning-configuration Status=Enabled
  aws s3api put-bucket-encryption --bucket "$BUCKET" \
    --server-side-encryption-configuration \
    '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'
  aws s3api put-public-access-block --bucket "$BUCKET" \
    --public-access-block-configuration \
    'BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true'
fi

cat > backend.hcl <<EOF
bucket       = "$BUCKET"
key          = "radiobot/terraform.tfstate"
region       = "$REGION"
use_lockfile = true
EOF
echo "Wrote backend.hcl"

tofu init -backend-config=backend.hcl -migrate-state -force-copy -input=false
echo "Done. State now lives in s3://$BUCKET/radiobot/terraform.tfstate"
